### PR TITLE
Assignment done

### PR DESCRIPTION
**Pull request by Omotade-MY**

### CODE REVIEW

**Review by Taiwrash — CHANGES_REQUESTED** [review]
### Break codebase by changing the library name ):
Check [x] the following, if they are properly added to your attendance file!

[ ] Added feedbacks
[ ] Added my goals for attending the class
[ ] Why will you attend next class?

- Will you attend next class
[ ] I will attend next class

**Review by Taiwrash — CHANGES_REQUESTED** [review]
There are a lot of typos 😃

Try fixing them🙂

**Comment by Omotade-MY** [comment]
Try merge it for me like that na 😃

**Review by Taiwrash — COMMENTED** [review]
LGTM

**Pull request merged**
